baseURL = 'https://arch.linuxrepos.org/'
languageCode = 'en-us'
theme = "archlinux"
title = 'LinuxRepos'
summaryLength = 8

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per site
paginate = 10


[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2
[[menu.main]]
identifier = "packages"
name = "Packages"
url = "/packages/"
weight = 3

[[menu.second]]
identifier = "contact"
name = "Contact"
url = "https://github.com/The-Repo-Club/Feedback/issues/new"
weight = 1
[[menu.second]]
identifier = "privacy"
name = "Privacy"
url = "/privacy"
weight = 2

[[menu.sponsors]]
identifier = "contact"
name = "Contact"
url = "https://github.com/The-Repo-Club/Feedback/issues/new"
weight = 1
[[menu.sponsors]]
identifier = "privacy"
name = "Privacy"
url = "/privacy"
weight = 2

[[menu.social]]
identifier = "github"
name = "Github"
url = "https://github.com/MinimalistCSS"
weight = 1
[[menu.social]]
identifier = "rss"
name = "RSS Feed"
url = "/index.xml"
weight = 2

[params]
# Tell me who you're
author = "Wayne Wesley"
location = ""
site_description = ""
copyright  = "Powered by [Hugo](//gohugo.io). Theme by [linuxrepos.org](https://github.com/The-Repo-Club/arch.linuxrepos.org)."
disclaimer = "_Disclaimer: This is a personal weblog. The opinions expressed here represent my own and not those of any entity in which I have been, am now, or will be affiliated._"

date_format = "2 Jan, 2006"

[[params.menu]]
before = true
label  = "Home"
link   = "/"

[[params.menu]]
before = false
label  = "Tags"
link   = "tags/"

[[params.menu]]
before = false
label  = "Categories"
link   = "categories/"

# Enable and disable widgets for the right sidebar
[params.widgets]
categories = false
documentation = false
downloads = false
recent_articles = true
search = true
tags = false
tag_cloud = false

[params.home]
old_posts = true
recent_packages = false
recent_posts = true
support = false

[outputs]
home = ["HTML", "RSS"]


[permalinks]
posts = "/posts/:year/:month/:day/:slug"